import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import 'bootstrap/dist/css/bootstrap.min.css';
import Header from "./components/Header";
import '@fortawesome/fontawesome-free/css/all.min.css';




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
     
        <header>
        <div className="relative z-50">
 
  <Header /> 

</div>

          </header>     
      
        <main>

          {children}
          </main>
        <footer>
          <Footer/>
        </footer>
      
      </body>
    </html>
  );
}
